environments:
  
  crafteo:
    variables:
    - name: SANDBOX_ENVIRONMENT
      value: crafteo
    - name: AWS_DEFAULT_REGION
      value: eu-west-3
  
  ami-template:
    variables:
    - name: SANDBOX_ENVIRONMENT
      value: ami-template
    - name: AWS_DEFAULT_REGION
      value: eu-west-3

config:
  default:
    environment: crafteo