config:
  # Optionally specify AWS region (use default region from config if unset)
  # aws:region: eu-west-3
  cloud-sandbox-eks:environment: crafteo
  cloud-sandbox-eks:hostedZoneName: k8s.crafteo.io