# Wait for connectivity and Nix switch
- hosts: all
  gather_facts: false  
  remote_user: root
  pre_tasks:
    - name: Wait for connectivity
      ansible.builtin.wait_for_connection:
        timeout: 10
      register: wait_connect_result
      until: wait_connect_result is success
      retries: 18
      delay: 10

    - name: gather facts
      tags: [ always ]
      gather_facts:
  
  tasks:
    - name: nixos-rebuild switch
      become: true
      ansible.builtin.command: 
        cmd: nixos-rebuild switch

# Sandbox additional config
- hosts: all
  remote_user: "{{ sandbox_user }}"
  vars:
    # Git repositories to be cloned in home directory
    cloud_sandbox_clone_git_repos:
    - name: example-voting-app
      repo: 'https://github.com/PierreBeucher/example-voting-app.git'
    - name: k8s-training
      repo: 'https://github.com/PierreBeucher/k8s-training-exercises'
  
  tasks:
    - name: clone Git repos
      tags: [ git ]
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ ansible_env.HOME }}/{{ item.name }}"
      loop: "{{ cloud_sandbox_clone_git_repos }}"
      notify: reboot system # Have system reboot on initial install

  handlers:
    - name: reboot system
      become: true
      ansible.builtin.reboot:
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 10
        search_paths: ["/sbin", "/bin", "/usr/sbin", "/usr/bin", "/usr/local/sbin", "/run/current-system/sw/bin"]